name: LeetCode Daily Push

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 0 点 → 北京时间 8 点
  workflow_dispatch:     # 手动触发

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run LeetCode Push
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          LEETCODE_DOMAIN: ${{ secrets.LEETCODE_DOMAIN }}
        run: |
          python index.py
