name: LeetCode Daily Push

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: '0 9 * * *'  # 可选：每天 9 点自动触发

jobs:
  push_daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LeetCode push
        run: python index.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
